fun main() {
    println("Hello, Android!")
    println("Hello, Android!")
    
    println("Hello, FADHIL PRAWIRA!")

    // println("Today is sunny!) // return error, need "
    println("Today is sunny!")
    
    println("1")
    println("2")
    println("3")

    println("I'm")
    println("learning")
    println("Kotlin!")

    println("Monday")
    println("Tuesday")
    println("Wednesday")
    println("Thursday")
    println("Friday")
    
    println("Tomorrow is rainy")
    // printLine("There is a chance of snow") // return error, wrong code
    println("There is a chance of snow")

    // println("Cloudy") println("Partly Cloudy") println("Windy") //return error, kotlin can not print in one line
    println("Cloudy")
    println("Partly Cloudy")
    println("Windy")

    println("How's the weather today?")
}
